# Generated by Django 5.2 on 2025-05-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AidBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], default='denied', max_length=10)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid.aidtype')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('distribution_date', models.DateField()),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid.aidtype')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid.aidbeneficiary')),
            ],
        ),
    ]
