# Generated by Django 5.2 on 2025-05-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('aid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid.aidtype')),
            ],
        ),
    ]
