# Generated by Django 5.2 on 2025-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_aidapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
