# Generated by Django 5.2 on 2025-05-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_alter_aidtype_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
